### ISSUE TITLE
Support for Steam Controller

### ISSUE THREAD

**Issue by Richm246** [jfernandez/ControllerTools#31]
My Steam Controller works flawlessly with my Steam Deck, but it doesn't show up in Controller Tools, it's connected via Bluetooth.

**Comment by ergoithz** [comment]
The Steam Controller may be disabled by vendor id (probably to hide Steam Deck inputs): hhttps://github.com/alphamercury/ControllerTools/blob/0e9b5ceaeb87142fc352d7ebb0fd31eb30d54ed5/backend/src/api/generic.rs#L14-L15

**Comment by Richm246** [comment]
Thanks for the reply, I appreciate it

**Comment by karasuhebi** [comment]
> Thanks for the reply, I appreciate it

So can this be closed?

**Comment by Nottinghster** [comment]
@jfernandez this can be closed!
