### ISSUE TITLE
Feature Request: add support for Xbox Elite Wireless Controller Series 2

### ISSUE THREAD

**Issue by isitLoVe** [jfernandez/ControllerTools#39]
Should be easy if you know the hardware id and add it to xbox.rs.

See also: https://www.pcgamingwiki.com/wiki/Controller:Xbox_Elite_Wireless_Controller_Series_2#Technical_informationhttps://www.pcgamingwiki.com/wiki/Controller:Xbox_Elite_Wireless_Controller_Series_2#Technical_information

(B)(root@steamdeck ~)# lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 13d3:3553 IMC Networks Bluetooth Radio
Bus 003 Device 002: ID 28de:1205 Valve Software Steam Controller
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

[ 1166.103782] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B22.0008/input/input36
[ 1166.104065] input: Xbox Wireless Controller Consumer Control as /devices/virtual/misc/uhid/0005:045E:0B22.0008/input/input37
[ 1166.104272] input: Xbox Wireless Controller Keyboard as /devices/virtual/misc/uhid/0005:045E:0B22.0008/input/input38
[ 1166.104603] hid-generic 0005:045E:0B22.0008: input,hidraw4: BLUETOOTH HID v5.17 Gamepad [Xbox Wireless Controller] on 50:5a:65:a1:43:70
[ 1166.393183] input: Microsoft X-Box 360 pad 1 as /devices/virtual/input/input39
[ 1166.103782] input: Xbox Wireless Controller as /devices/virtual/misc/uhid/0005:045E:0B22.0008/input/input36
[ 1166.104065] input: Xbox Wireless Controller Consumer Control as /devices/virtual/misc/uhid/0005:045E:0B22.0008/input/input37
[ 1166.104272] input: Xbox Wireless Controller Keyboard as /devices/virtual/misc/uhid/0005:045E:0B22.0008/input/input38
[ 1166.104603] hid-generic 0005:045E:0B22.0008: input,hidraw4: BLUETOOTH HID v5.17 Gamepad [Xbox Wireless Controller] on 50:5a:65:a1:43:70
[ 1166.393183] input: Microsoft X-Box 360 pad 1 as /devices/virtual/input/input39

bluetoothctl
[Xbox Wireless Controller]# info
Device F4:6A:D7:49:74:35 (public)
        Name: Xbox Wireless Controller
        Alias: Xbox Wireless Controller
        Appearance: 0x03c4
        Icon: input-gaming
        Paired: yes
        Trusted: yes
        Blocked: no
        Connected: yes
        WakeAllowed: yes
        LegacyPairing: no
        UUID: Vendor specific           (00000001-5f60-4c4f-9c83-a7953298d40d)
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Device Information        (0000180a-0000-1000-8000-00805f9b34fb)
        UUID: Battery Service           (0000180f-0000-1000-8000-00805f9b34fb)
        UUID: Human Interface Device    (00001812-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v045Ep0B22d0517
        Battery Percentage: 0x64 (100)

**Comment by isitLoVe** [comment]
I tried building the plugin with the new code and installing it, however it does not recognize the controller :(

**Comment by Nottinghster** [comment]
@jfernandez 
This is solved!
