### ISSUE TITLE
Cannot find latests releases in the Decky Store

### ISSUE THREAD

**Issue by Sebi11** [jfernandez/ControllerTools#53]
Hi!
Am I the only one? In the Decky Store, I cannot find the last versions of this plugin: the last one showing is 1.1.2-1. I'd like to install 1.2.x versions to get the fixes for the last Steam OS version. 
Regards

**Comment by Nottinghster** [comment]
We're just waiting for this: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/636

**Comment by Sebi11** [comment]
Okay, sorry, I wasn't aware of the process.
