### ISSUE TITLE
Not able to see latest release in decky store

### ISSUE THREAD

**Issue by dsk001** [jfernandez/ControllerTools#54]
I have the original steam deck on the stable release 3.5.19 with decky loader 2.12.3 install. 
When I go to the plug in store the latest version of controller tools I see is 1.1.2-1 which is currently not loading properly.

**Comment by blokie13** [comment]
This is happening on OLED too (latest showing is 1.1.2-1), not just LCD model.  I'm on 3.5.19 with decky loader v2.12.2-pre1

When you click on the Controller Tools option in the menu you get an error:

TypeError: Cannot read properties of undefined (reading 'Title')
  at eval (eval at importReactPlugin (http://localhost:1337/frontend/chunk-00b6e60c.js:6984:43), <anonymous>:428:84)
  at eval (eval at importReactPlugin (http://localhost:1337/frontend/chunk-00b6e60c.js:6984:43), <anonymous>:132:20)
at Pluginloader.importReactPlugin (http://localhost:1337/frontend/chunk-00b6e60c.js:6985:30)
at async Pluginloader.importPlugin (http://localhost:1337/frontend/chunk-00b6e60c.js:6959:17)

**Comment by martintou** [comment]
same issue for my steam deck oled

**Comment by Hotsolce** [comment]
I also have this issue, I get the feeling that more recent versions may need to be rebuilt and pushed to the plug-in store again.
The most recent versions aren't listed in the repository's json file (https://wiki.deckbrew.xyz/en/user-guide/plug-in-store).

I think we're just going to all have to be patient and wait for our authors to come back and take a look.

**Comment by michaljuris** [comment]
We just need to patiently wait for @jfernandez to sort this issue out:
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/636 

(there is a little confusion since in https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/632#issuecomment-2136099743 was pnpm 6.0 requested, but in the new one they requested the latest version)

**Comment by Nottinghster** [comment]
The fix is ready, but not merged yet
But if you want to use it anyway, active developer mode in Decky Loader, and then, import this zip file
[controller-tools-1.2.0.zip](https://github.com/user-attachments/files/15806771/controller-tools-1.2.0.zip)

![rn_image_picker_lib_temp_cd92cb6e-9633-492f-ba6b-18db5d5c80fa](https://github.com/jfernandez/ControllerTools/assets/7372287/ed1d9242-dde3-44d0-a85d-d77d7bdd5b54)

**Comment by jfernandez** [comment]
I will aim to get the plugin published by the end of the week. Apologies for the delay, work/life has kept me busy!

**Comment by Nottinghster** [comment]
> would this fall under the stable release channel?

Just waiting for this
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/647

**Comment by Nottinghster** [comment]
Already merged

@jfernandez can close this issue ;)

**Comment by dm82m** [comment]
Now we have version 1.2.2 in decky but still broken with another error:

![image](https://github.com/user-attachments/assets/194a96ed-8dfa-48f4-9e60-09b7c550cfee)

**Comment by Sportela20** [comment]
Hello all! Is this still having issues? Found myself unable to install the plugin, even through developer mode. Tks!

**Comment by mlusic** [comment]
Same problem here, still can not find plugin in decky store.

**Comment by tpkee** [comment]
Same

**Comment by costinvader** [comment]
I had to find the Decky plugins folder and manually put every file in a folder called like the plugin and restart the deck. You have to download it from here in github and do it everything manually

**Comment by Sportela20** [comment]
I had done that before and the plugin was working but with the introduction of Decky 3.0, the zip does not work and it doesn't seem go allow us to write a link in Developer mode, as it did before. Suggestions?

**Comment by Sportela20** [comment]
![17266563789131708191897656561554](https://github.com/user-attachments/assets/aa594d40-ef1f-4555-852d-ac9d7451b6bd)

As a reference, attempts to uninstall and reinstall have been unsuccessfull, and when I restart the deck it returns and it has this error. I am led to believe the plug-in is not compatible with Decky 3.0 quite honestly.

**Comment by MrArdillo** [comment]
Someone knows if these plugin is still supported by the creator I loved it so much and know I miss it

**Comment by eXhumer** [comment]
I have opened a PR with fix (#56).

If anyone wants to try it, use the following link to download a development build from [here](https://nightly.link/eXhumer/ControllerTools/workflows/dev-build/main/Controller%20Tools.zip).

**Comment by Sportela20** [comment]
> I have opened a PR with fix (#56).
> 
> If anyone wants to try it, use the following link to download a development build from [here](https://nightly.link/eXhumer/ControllerTools/workflows/dev-build/main/Controller%20Tools.zip).

This worked, yay!

**Comment by dm82m** [comment]
it works, thank you @eXhumer - maybe it would be an idea to fork the project and take over the further development as original author seems to be absent!?

**Comment by jfernandez** [comment]
Hi all, maintainer here. I cannot continue to work on this plugin. Thank you, @eXhumer, for getting it back to a working state. Before I merge the PR, I suggest we align on how to maintain this plugin in the future. I can think of two options:

* We can make you the co-maintainer of the project.
or
* You can fork it as suggested and own that fork. Since it has been delisted, I do not plan to re-submit the plugin to the Decky store.

**Comment by dm82m** [comment]
Thanks for all your work @jfernandez!

I personally don’t mind the way we go as long as we have it up and running. So first we need @eXhumer to be willing to take over and then he can decide the way he wants to go.

**Comment by eXhumer** [comment]
I would prefer to be co-maintainer rather than just taking over the project, but I'm willing to do whatever works best for you.

**Comment by MrArdillo** [comment]
> I have opened a PR with fix (#56).
> 
> If anyone wants to try it, use the following link to download a development build from [here](https://nightly.link/eXhumer/ControllerTools/workflows/dev-build/main/Controller%20Tools.zip).

It works but I don't know why it doesn't work with the 8bitdo pro controller 2 on xinput mode but it switch mode it does

**Comment by eXhumer** [comment]
> > I have opened a PR with fix (#56).
> > If anyone wants to try it, use the following link to download a development build from [here](https://nightly.link/eXhumer/ControllerTools/workflows/dev-build/main/Controller%20Tools.zip).
> 
> It works but I don't know why it doesn't work with the 8bitdo pro controller 2 on xinput mode but it switch mode it does

That is an issue with 8BitDo controller itself not reporting the battery in XInput mode.

**Comment by MrArdillo** [comment]
> > > I have opened a PR with fix (#56).
> > > If anyone wants to try it, use the following link to download a development build from [here](https://nightly.link/eXhumer/ControllerTools/workflows/dev-build/main/Controller%20Tools.zip).
> > 
> > It works but I don't know why it doesn't work with the 8bitdo pro controller 2 on xinput mode but it switch mode it does
> 
> That is an issue with 8BitDo controller itself not reporting the battery in XInput mode.

Yes, I saw that later searching for the issue. Thanks for the answer!

**Comment by jfernandez** [comment]
@eXhumer I sent you an invite to be a collaborator. I’ve also merged your PR. Please feel free to cut the new release (2.0.0) and resubmit the plugin to the Decky store.

**Comment by eXhumer** [comment]
Thanks. I submitted a [PR at decky-plugin-database](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/708) to get the plugin back into testing score.

**Comment by eXhumer** [comment]
The plugin is now available in the testing channel of Decky Store and can be downloaded directly if you switch to the test channel. If anyone has the time, please submit a test report in PR to decky-plugin-database to expedite the process of it being returned the release store.

**Comment by eXhumer** [comment]
Controller Tools is now available in the production channel of Decky Store.

If there any issues, feel free to open an issue detailing it.
