### ISSUE TITLE
Bazzite 

### ISSUE THREAD

**Issue by Hazardpup77** [jfernandez/ControllerTools#55]
Ok I am running bazzite os and installed decks but controller tools isn't showing up on the available downloads I am guessing it's because it's not true steam os but was wondering if I was right or if I'm doing something wrong

**Comment by jfernandez** [comment]
We only support SteamOS

**Comment by Hazardpup77** [comment]
Just wanted to ask sorry for bothering you on this just wanted to make sure I wasn't missing something my steam deck failed so I worked on just getting the closest thing I could on a 1yr old amd mini pc I had laying around but thank again for your time and sorry for bothering you
