### ISSUE TITLE
I dont see this in the plugin store

### ISSUE THREAD

**Issue by Saigaiii** [jfernandez/ControllerTools#57]
running stable on steamdeck and this plugin doesnt come up.

**Comment by f3bandit** [comment]
> running stable on steamdeck and this plugin doesnt come up.

you have to manually download and install it for now. go into desktop mode and download 
[ControllerTools](https://github.com/jfernandez/ControllerTools/releases/)
the go back to gaming mode open deckyloader and goto settings.
enable dev mode. from the dev mode install the ControllerTools.zip you downloaded.
The original maintainer is super busy and cannot devote enough time to the project.
someone else is taking over so there will be a bit of juggling until everything is in place
for it to be submitted to the plugin store. so for now manual install.

**Comment by eXhumer** [comment]
See #54.

The plugin is now available in the testing store.

You can expedite the process of it being returned back to the release channel of Decky Store if you submit a test report with if anything is not working as intended or if everything is working as expected in the PR to decky-plugin-database.
